#set up by Nephi
#validate this file here: http://lint.travis-ci.org/
sudo: required
language: cpp
compiler:
  - g++

install:
  - sudo apt-get sdl-dev

script:  make clean && make && ./build/./PacMan-Clone.exe
#script: make clean && make deploy #&& ./build/./PacMan-Clone.exe
