#set up by Nephi
#WORK ALREADY!!!!
#validate this file here: http://lint.travis-ci.org/
#sudo: required

language: cpp
compiler:
 - g++

 #before_install:

install:
 - wget https://www.libsdl.org/release/SDL-devel-1.2.15-1.x86_64.rpm
 - sudo apt-get install alien
 #alien converts rpm to deb, ubuntu can only install deb
 - sudo alien SDL-devel-1.2.15-1.x86_64.rpm
 - sudo dpkg -i sdl-devel_1.2.15-2_amd64.deb
  
  
#after_install:
  
before_script:
 #if build directory doesn't exist, make it
 - if [! -d "build" ]; then
 -   mkdir build
 - if

script:  make clean && make
#We are making a game, this uses a lot of user interaction. Running the build is probably something that should not be done with Travis.
#&& ./build/./PacMan-Clone.exe


#after_success:

#after_failure:

#after_script:
 